-- MySQL Script generated by MySQL Workbench
-- Wed Feb  2 11:26:47 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema employees_system
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `employees_system` ;

-- -----------------------------------------------------
-- Schema employees_system
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `employees_system` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `employees_system` ;

-- -----------------------------------------------------
-- Table `employees_system`.`Compensation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `employees_system`.`Compensation` ;

CREATE TABLE IF NOT EXISTS `employees_system`.`Compensation` (
  `type` INT NOT NULL,
  `amount` INT NOT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  `date` DATETIME NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `employees_system`.`Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `employees_system`.`Employee` ;

CREATE TABLE IF NOT EXISTS `employees_system`.`Employee` (
  `uid` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `middle_name` VARCHAR(45) NULL DEFAULT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `position` VARCHAR(45) NOT NULL,
  `birth_date` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`uid`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `employees_system`.`Type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `employees_system`.`Type` ;

CREATE TABLE IF NOT EXISTS `employees_system`.`Type` (
  `idType` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idType`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
