-- MySQL Script generated by MySQL Workbench
-- Wed Feb  2 11:26:47 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema employees_system
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `employees_system` ;

-- -----------------------------------------------------
-- Schema employees_system
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `employees_system` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `employees_system` ;

-- -----------------------------------------------------
-- Table `employees_system`.`Compensation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `employees_system`.`Compensation` ;

CREATE TABLE IF NOT EXISTS `employees_system`.`Compensation` (
  `id` int NOT NULL,
  `type` int NOT NULL,
  `amount` int NOT NULL,
  `description` varchar(45) DEFAULT NULL,
  `date` datetime NOT NULL,
  `idEmployee` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `type_idx` (`type`),
  KEY `idEmployee_idx` (`idEmployee`),
  CONSTRAINT `idEmployee` FOREIGN KEY (`idEmployee`) REFERENCES `Employee` (`uid`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `type` FOREIGN KEY (`type`) REFERENCES `Type` (`idType`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `Compensation`
--

LOCK TABLES `Compensation` WRITE;
/*!40000 ALTER TABLE `Compensation` DISABLE KEYS */;
INSERT INTO `Compensation` VALUES (1,1,30000,'salary','2019-05-10 00:00:00',1);
/*!40000 ALTER TABLE `Compensation` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

-- -----------------------------------------------------
-- Table `employees_system`.`Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `employees_system`.`Employee` ;

CREATE TABLE IF NOT EXISTS `employees_system`.`Employee` (
  `uid` int NOT NULL AUTO_INCREMENT,
  `firstName` varchar(45) NOT NULL,
  `middleName` varchar(45) DEFAULT NULL,
  `lastName` varchar(45) NOT NULL,
  `position` varchar(45) NOT NULL,
  `birthDate` date NOT NULL,
  `idCompensation` int DEFAULT NULL,
  PRIMARY KEY (`uid`),
  KEY `idCompensation_idx` (`idCompensation`),
  CONSTRAINT `idCompensation` FOREIGN KEY (`idCompensation`) REFERENCES `Compensation` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=27 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `Employee`
--

LOCK TABLES `Employee` WRITE;
/*!40000 ALTER TABLE `Employee` DISABLE KEYS */;
INSERT INTO `Employee` VALUES (1,'Ale','','Centeno','Student','1999-06-10',1),(2,'Jose','','Perez','Employee','1995-06-04',NULL),(3,'Manuel','','Mora','Employee','1984-07-06',NULL),(4,'Sandra','','Gomez','Employee','1998-02-17',NULL);
/*!40000 ALTER TABLE `Employee` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;


-- -----------------------------------------------------
-- Table `employees_system`.`Type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `employees_system`.`Type` ;

CREATE TABLE IF NOT EXISTS `employees_system`.`Type` (
 `idType` int NOT NULL,
  `name` varchar(45) NOT NULL,
  PRIMARY KEY (`idType`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `Type`
--

LOCK TABLES `Type` WRITE;
/*!40000 ALTER TABLE `Type` DISABLE KEYS */;
INSERT INTO `Type` VALUES (1,'Salary'),(2,'Bonus'),(3,'Commision'),(4,'Allowance'),(5,'Adjustment');
/*!40000 ALTER TABLE `Type` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

-- -----------------------------------------------------
-- Table `employees_system`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `employees_system`.`User` ;

CREATE TABLE `User` (
  `id` int NOT NULL AUTO_INCREMENT,
  `email` varchar(45) NOT NULL,
  `password` varchar(64) NOT NULL,
  `name` varchar(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `email_UNIQUE` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=18 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `User`
--

LOCK TABLES `User` WRITE;
/*!40000 ALTER TABLE `User` DISABLE KEYS */;
INSERT INTO `User` VALUES (1,'rramirez@ibm.com','$2a$10$u0H7WV6sNEFSg1TCCEUoQ./P1h./vvYdRDfyF66HrCjflinRSw9DO',''),(17,'alecenteno@ibm.com','$2a$10$cCMBoWCzHe2eeaLs7Trz8eFAdwc3K6uG77jx2xnoQCun7eQDW4QA6','Ale');
/*!40000 ALTER TABLE `User` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;
